/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javaswingdev.dialog;

import Restaurant.Database.ConnectionFactory;
import Restaurant.UI.POS;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import static javax.swing.SwingConstants.LEFT;
import static javax.swing.SwingConstants.RIGHT;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kalan
 */
public class Cansel_Invoice extends javax.swing.JDialog {
    java.sql.Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * Creates new form OngoingKOT
     */
    public Cansel_Invoice(Frame parent, boolean modal, String user) {
        super(parent, modal);
        initComponents();
        conn = new ConnectionFactory().getConn();
        loadInvoice();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        btnCansel = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lb1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnCansel1 = new javax.swing.JButton();
        lb2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCansel.setBackground(new java.awt.Color(0, 51, 51));
        btnCansel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCansel.setForeground(new java.awt.Color(255, 255, 255));
        btnCansel.setText("CANSEL");
        btnCansel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanselActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 51, 51));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        lb1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(125, 125, 125));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("INVOICE CANCEL");

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblInvoice.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInvoiceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblInvoiceMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblInvoice);

        btnExit.setBackground(new java.awt.Color(153, 0, 0));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnCansel1.setBackground(new java.awt.Color(0, 51, 51));
        btnCansel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCansel1.setForeground(new java.awt.Color(255, 255, 255));
        btnCansel1.setText("REPTINT");
        btnCansel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCansel1ActionPerformed(evt);
            }
        });

        lb2.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        lb2.setForeground(new java.awt.Color(125, 125, 125));
        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("INV-");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(lb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb1)
                                    .addGroup(pnlMainLayout.createSequentialGroup()
                                        .addComponent(btnCansel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCansel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 333, Short.MAX_VALUE))
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane3))
                        .addContainerGap())))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txtSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCansel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCansel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(901, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanselActionPerformed
        // TODO add your handling code here:
        cansal();
    }//GEN-LAST:event_btnCanselActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:DefaultTableModel model1 =(DefaultTableModel)jTable1.getModel();
        reset();
        txtSearch.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInvoiceMouseClicked
        // TODO add your handling code here:
//        tblItem.getSelectionModel().clearSelection();
//        int SelectRow = this.tblInvoice.getSelectedRow();
//        refNo = tblInvoice.getValueAt(SelectRow ,0).toString();
//        tblInvoice.getValueAt(SelectRow ,1).toString();
    }//GEN-LAST:event_tblInvoiceMouseClicked

    private void tblInvoiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInvoiceMousePressed
        // TODO add your handling code here:
//        if (evt.getClickCount() == 2 && tblInvoice.getSelectedRow() != -1) {
//            int SelectRow = this.tblInvoice.getSelectedRow();
//            
//            refNo = tblInvoice.getValueAt(SelectRow ,0).toString();            
//            
//            getItem(refNo);
            
            
            
            
//            txtDescription.setText(table.getValueAt(SelectRow, 1).toString());
//            jDateChooser.setDate((Date)table.getModel().getValueAt(SelectRow, 2));
//            
//            String date = table.getValueAt(table.getSelectedRow(),2).toString();
//            java.util.Date date2 = null;
//            try {
//                date2 = new SimpleDateFormat("yyyy-MM-dd").parse(date);
//                dteDate.setDate(date2);
//            } catch (ParseException ex) {
//                Logger.getLogger(Form_Expense.class.getName()).log(Level.SEVERE, null, ex);
//            }
            
//            NumberFormat formatter = new DecimalFormat("0.00");
//            txtAmount.setText(formatter.format(Double.parseDouble(String.valueOf(table.getValueAt(table.getSelectedRow(),3).toString()))));
//        }
    }//GEN-LAST:event_tblInvoiceMousePressed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnCansel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCansel1ActionPerformed
        // TODO add your handling code here:
        if (tblInvoice.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Please select the Invoice");
        else {
            int response1 = JOptionPane.showConfirmDialog(null, "Are you want to print this invoice?", "confirmation", JOptionPane.YES_NO_OPTION);
            if (response1 == JOptionPane.YES_OPTION) {
                int r = tblInvoice.getSelectedRow();
                String inv = tblInvoice.getValueAt(r,0).toString().trim();
                printInvoice(inv);
                reset();
            }
        }
    }//GEN-LAST:event_btnCansel1ActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cansel_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cansel_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cansel_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cansel_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String user = null;
                Cansel_Invoice dialog = new Cansel_Invoice(new javax.swing.JFrame(), true, user);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCansel;
    private javax.swing.JButton btnCansel1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadInvoice() {
        try {
            String sql1 = "SELECT Inv_No, Date, Time, Trans_Type, Total_Amount, Service_Charge, Net_Amount, User FROM t10invoice_resturent WHERE Status='A' ORDER BY Inv_No DESC";
            ps=conn.prepareStatement(sql1);
            rs=ps.executeQuery();
            tblInvoice.setModel(DbUtils.resultSetToTableModel(rs));
            setAlignment();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    

    private void cansal() {        
        if (tblInvoice.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Please select the Invoice");
        else {
            int opt = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to Delete this Invoice?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt==JOptionPane.YES_OPTION) {
                
                int r = tblInvoice.getSelectedRow();
                String inv = tblInvoice.getValueAt(r,0).toString();
                try {
                    ps = conn.prepareStatement("UPDATE t10invoice_resturent SET Status =? WHERE Inv_No=?");
                    ps.setString(1, "I");
                    ps.setString(2,inv);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Invoice is Canseled");
                    loadInvoice();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }
        }
    }

    private void Search() {
        String txt = txtSearch.getText();
        String search = "INV-"+txt;
        
        try {
            String sql1 = "SELECT Inv_No, Date, Time, Trans_Type, Total_Amount, Service_Charge, Net_Amount, User FROM t10invoice_resturent WHERE Inv_No like '%"+search+"%' AND Status='A' ORDER BY Inv_No DESC";
            ps=conn.prepareStatement(sql1);
            rs=ps.executeQuery();
            tblInvoice.setModel(DbUtils.resultSetToTableModel(rs));
            setAlignment();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void reset() {
        loadInvoice();
        txtSearch.setText("");
    }
    
    
    private void printInvoice(String invoiceNo) {
        
        HashMap m = new HashMap();
        m.put("invoiceNo", invoiceNo);
        try {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\kalan\\JaspersoftWorkspaceV2\\Restaurant\\Invoice_Restaurant.jrxml");
            JasperReport ireport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(ireport, m,conn);

            JasperViewer.viewReport(jprint,false);
//                JasperPrintManager.printReport(jprint, false);               
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
           // Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        } 
    } 
    
    
    private void setAlignment() {
        DefaultTableCellRenderer rightRender = new DefaultTableCellRenderer();
        rightRender.setHorizontalAlignment(RIGHT);
        DefaultTableCellRenderer leftRender = new DefaultTableCellRenderer();
        leftRender.setHorizontalAlignment(LEFT);
//        table.getColumnModel().getColumn(0).setHeaderRenderer(leftRender);
//        table.getColumnModel().getColumn(1).setHeaderRenderer(leftRender);
//        table.getColumnModel().getColumn(2).setHeaderRenderer(leftRender);
//        table.getColumnModel().getColumn(3).setHeaderRenderer(rightRender);
//        table.getColumnModel().getColumn(4).setHeaderRenderer(rightRender);
//        table.getColumnModel().getColumn(5).setHeaderRenderer(rightRender);
//        
        tblInvoice.getColumnModel().getColumn(4).setCellRenderer(rightRender);
        tblInvoice.getColumnModel().getColumn(5).setCellRenderer(rightRender);
        tblInvoice.getColumnModel().getColumn(6).setCellRenderer(rightRender);
        tblInvoice.getColumnModel().getColumn(7).setCellRenderer(rightRender);
//        tblInvoice.getColumnModel().getColumn(3).setCellRenderer(rightRender);
    }

}
