/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javaswingdev.dialog;

import Restaurant.DAO.CategoryDAO;
import Restaurant.Database.ConnectionFactory;
import Restaurant.UI.POS;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author kalan
 */
public class Ongoing extends javax.swing.JDialog {
    java.sql.Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    PreparedStatement ps1 = null;
    ResultSet rs1 = null;
    String refNo;
    String dineIn;
    private POS  mainPOS;
    String userName;

    /**
     * Creates new form OngoingKOT
     * @param parent
     */
    public Ongoing(Frame parent, boolean modal, String user) {
        super(parent, modal);
        initComponents();
        conn = new ConnectionFactory().getConn();
        tableKOT();
        btnCanselKOT.setEnabled(false);
        userName=user;
    }

    Ongoing() {
        initComponents();
        conn = new ConnectionFactory().getConn();
        tableKOT();
        btnCanselKOT.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        btnCanselKOT = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOngoin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCanselKOT.setBackground(new java.awt.Color(153, 0, 0));
        btnCanselKOT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCanselKOT.setForeground(new java.awt.Color(255, 255, 255));
        btnCanselKOT.setText("Cansel KOT");
        btnCanselKOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanselKOTActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(153, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("EXIT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btnPay.setBackground(new java.awt.Color(0, 51, 51));
        btnPay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Complete");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblItem);

        btnReset.setBackground(new java.awt.Color(0, 51, 51));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        lb1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(125, 125, 125));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("Ongoing Orders");

        lb2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lb2.setForeground(new java.awt.Color(125, 125, 125));
        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("KOT List");

        tblOngoin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblOngoin.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblOngoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOngoinMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblOngoinMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblOngoin);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant/UI/Icons/icons8-refresh-48.png"))); // NOI18N
        jLabel1.setText("Refresh");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb2)
                            .addComponent(btnCanselKOT))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(lb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCanselKOT, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(901, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanselKOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanselKOTActionPerformed
        // TODO add your handling code here:
        cansal();
    }//GEN-LAST:event_btnCanselKOTActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        if (tblOngoin.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Select a Ongoing Order");
        else {
            Payment payment = new Payment(mainPOS, true, refNo, dineIn, userName);
            payment.setVisible(true);
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        // TODO add your handling code here:
        tblOngoin.getSelectionModel().clearSelection();
        btnCanselKOT.setEnabled(true);
    }//GEN-LAST:event_tblItemMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:DefaultTableModel model1 =(DefaultTableModel)jTable1.getModel();
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblOngoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOngoinMouseClicked
        // TODO add your handling code here:
        tblItem.getSelectionModel().clearSelection();
        int SelectRow = this.tblOngoin.getSelectedRow();
        refNo = tblOngoin.getValueAt(SelectRow ,0).toString();
        dineIn = tblOngoin.getValueAt(SelectRow ,1).toString();
    }//GEN-LAST:event_tblOngoinMouseClicked

    private void tblOngoinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOngoinMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && tblOngoin.getSelectedRow() != -1) {
            int SelectRow = this.tblOngoin.getSelectedRow();
            
            refNo = tblOngoin.getValueAt(SelectRow ,0).toString();            
            
            getItem(refNo);
            
            
            
            
//            txtDescription.setText(table.getValueAt(SelectRow, 1).toString());
//            jDateChooser.setDate((Date)table.getModel().getValueAt(SelectRow, 2));
//            
//            String date = table.getValueAt(table.getSelectedRow(),2).toString();
//            java.util.Date date2 = null;
//            try {
//                date2 = new SimpleDateFormat("yyyy-MM-dd").parse(date);
//                dteDate.setDate(date2);
//            } catch (ParseException ex) {
//                Logger.getLogger(Form_Expense.class.getName()).log(Level.SEVERE, null, ex);
//            }
            
//            NumberFormat formatter = new DecimalFormat("0.00");
//            txtAmount.setText(formatter.format(Double.parseDouble(String.valueOf(table.getValueAt(table.getSelectedRow(),3).toString()))));
        }
    }//GEN-LAST:event_tblOngoinMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ongoing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ongoing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ongoing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ongoing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String user = null;
                Ongoing dialog = new Ongoing(new javax.swing.JFrame(), true, user);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanselKOT;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblOngoin;
    // End of variables declaration//GEN-END:variables

    public void tableKOT() {
        try {
            String sql1 = "SELECT Ref_No, Order_To, SUM(Total) as Total_Amount FROM t06resturent_kot WHERE Paid='NO' AND Status='ACTIVE' GROUP BY Ref_No, Order_To";
            ps=conn.prepareStatement(sql1);
            rs=ps.executeQuery();
            tblOngoin.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    private void getItem(String refNo) {
        try {
            String sql1 = "SELECT k.Ref_No, k.KOT_No, i.Menu_Name, k.Price, k.Qty, k.Total, k.ID FROM t06resturent_kot k, m06menu_item i WHERE i.Menu_Code=k.Item_Code AND k.Paid=? AND k.Status=? AND k.Ref_No=? ";
            ps1 = conn.prepareStatement(sql1);
            ps1.setString(1,"NO");
            ps1.setString(2,"ACTIVE");
            ps1.setString(3,refNo);
            rs1=ps1.executeQuery();
            tblItem.setModel(DbUtils.resultSetToTableModel(rs1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    private void cansal() {        
        if (tblItem.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Please select the KOT");
        else {
            int opt = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to Cansel this KOT?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt==JOptionPane.YES_OPTION) {
                
                int r = tblItem.getSelectedRow();
                String id = tblItem.getValueAt(r,6).toString();
                try {
                    ps = conn.prepareStatement("UPDATE T06Resturent_KOT set Status =? where ID=?");
                    ps.setString(1, "CANSEL");
                    ps.setString(2,id);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "KOT Canseled");
                    tableKOT();
                    getItem(refNo);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }
        }
    }

    private void Search() {
//        String txt = txtSearch.getText();
//        String search = "RT-"+txt;
//        
//        try {
//            String sql2 = "select kot.Ref_No, kot.Table_No, kot.Inv_No, kot.Time, kot.item_Code, menu.Menu_Name, kot.Qty, kot.Status, kot.ID from T06Resturent_KOT kot, M06Menu_Item menu where kot.Item_Code= menu.Menu_Code and kot.Ref_No like '%"+search+"%' ";
//            ps=conn.prepareStatement(sql2);
//            rs=ps.executeQuery();
//            tblOngoin.setModel(DbUtils.resultSetToTableModel(rs));
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
    }

    private void reset() {
        DefaultTableModel model1 =(DefaultTableModel)tblItem.getModel();
        while(model1.getRowCount() > 0){
            for(int i=0; i< model1.getRowCount(); i++){
                model1.removeRow(i);
            }
        }
         tableKOT();
//        tblOngoin.getSelectionModel().clearSelection();
        btnCanselKOT.setEnabled(false);
        refNo="";
    }

}
