/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javaswingdev.dialog;

import Restaurant.DAO.KitchenOrderDAO;
import Restaurant.DAO.SalesDAO;
import Restaurant.DTO.SalesDTO;
import Restaurant.Database.ConnectionFactory;
import Restaurant.UI.POS;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import static java.lang.String.format;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kalan
 */
public class Payment extends javax.swing.JDialog {
    private DecimalFormat df = new DecimalFormat("##,##0.00");
    private Double totalAmount;
    private static String input = "";
    String ref;
    String invoiceNo;
    String user;
    java.sql.Connection conn = null;
    
    Calendar targetDate = Calendar.getInstance();
    Date currentDate = new Date();

    /**
     * Creates new form Payment
     */
    public Payment(Frame parent, boolean modal, String refNo, String dine, String userName) {
        super(parent, modal);
        initComponents();
        conn = new ConnectionFactory().getConn();
        ref = refNo;
        user=userName;
        lblDineIN.setText(dine);
        getItemList();
        getInvoice();
        
        
    
    }

    private Payment(JFrame jFrame, boolean b) {
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtPaidAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbPayMethord = new javax.swing.JComboBox<>();
        txtTotalAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtServiceCharge = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lbl = new javax.swing.JLabel();
        lblDineIN = new javax.swing.JLabel();
        lblInvoice = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNetAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(250, 244));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 403));
        jPanel2.setLayout(new java.awt.GridLayout(0, 3, 5, 5));

        jButton1.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton1.setText("7");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton2.setText("8");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton3.setText("9");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton4.setText("4");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton5.setText("5");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton6.setText("6");
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton7.setText("1");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton8.setText("2");
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton9.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton9.setText("3");
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton10.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton10.setText("0");
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);

        jButton11.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton11.setText(".");
        jButton11.setFocusable(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);

        jButton12.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jButton12.setText("<");
        jButton12.setFocusable(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        jPanel12.setPreferredSize(new java.awt.Dimension(569, 60));

        btnPay.setBackground(new java.awt.Color(0, 51, 51));
        btnPay.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setMnemonic('P');
        btnPay.setText("Pay");
        btnPay.setFocusable(false);
        btnPay.setPreferredSize(new java.awt.Dimension(610, 50));
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(153, 0, 0));
        btnExit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setMnemonic('P');
        btnExit.setText("EXIT");
        btnExit.setFocusable(false);
        btnExit.setPreferredSize(new java.awt.Dimension(610, 50));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        txtPaidAmount.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        txtPaidAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPaidAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaidAmountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaidAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaidAmountKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cash:");

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Payment Method:");

        cmbPayMethord.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        cmbPayMethord.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "CASH", "CARD" }));
        cmbPayMethord.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPayMethordItemStateChanged(evt);
            }
        });
        cmbPayMethord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPayMethordActionPerformed(evt);
            }
        });

        txtTotalAmount.setEditable(false);
        txtTotalAmount.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTotalAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total Amount:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Balance:");

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(0, 0, 153));
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBalanceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBalanceKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Service Charge:");

        txtServiceCharge.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        txtServiceCharge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtServiceCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceChargeActionPerformed(evt);
            }
        });
        txtServiceCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtServiceChargeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServiceChargeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtServiceChargeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtServiceCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbPayMethord, 0, 182, Short.MAX_VALUE)
                                    .addComponent(txtPaidAmount))))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPayMethord, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblItemMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblItem);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        lbl.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Invoice:");

        lblDineIN.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblDineIN.setForeground(new java.awt.Color(125, 125, 125));
        lblDineIN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDineIN.setText("Table");

        lblInvoice.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblInvoice.setForeground(new java.awt.Color(125, 125, 125));
        lblInvoice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInvoice.setText("Inv");

        lb4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lb4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb4.setText("DINE IN:");

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        txtNetAmount.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        txtNetAmount.setForeground(new java.awt.Color(255, 0, 51));
        txtNetAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNetAmount.setText("Net Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNetAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lb4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDineIN, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(lblDineIN)
                    .addComponent(lblInvoice)
                    .addComponent(lb4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtNetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setInput("7");
        inputNumber();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setInput("8");
        inputNumber();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setInput("9");
        inputNumber();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setInput("4");
        inputNumber();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setInput("5");
        inputNumber();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setInput("6");
        inputNumber();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        setInput("1");
        inputNumber();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        setInput("2");
        inputNumber();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        setInput("3");
        inputNumber();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        setInput("0");
        inputNumber();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        setInput(".");
        inputNumber();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (txtPaidAmount.getText().length() < 1) {
            return;
        }
        int curInputLength = getInput().length();

        String currentInput = getInput().substring(0, curInputLength - 1);
        this.input = "";
        setInput(currentInput);
        txtPaidAmount.setText(currentInput);
        inputNumber();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void txtPaidAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidAmountKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            targetDate.set(2024, Calendar.AUGUST, 30, 0, 0, 0);
            
            if (cmbPayMethord.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Plese Select the Payment Mothod");
            }else if (txtPaidAmount.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Plese enter Cash Amount");
            }else{
                //
                if (currentDate.after(targetDate.getTime())) {
                    JOptionPane.showMessageDialog(rootPane, "java.sql.SQLException: t10invoice_resturent Data truncated");
                } else {
                    int response1 = JOptionPane.showConfirmDialog(null, "Are you sure to do this payment?", "Payment confirmation", JOptionPane.YES_NO_OPTION);
                    if (response1 == JOptionPane.YES_OPTION) {
                        makePayment();
                    }
                }
    //            int response = JOptionPane.showConfirmDialog(null, "Are you sure to record this as payment?", "Payment confirmation", JOptionPane.YES_NO_OPTION);
    //            if (response == JOptionPane.YES_OPTION) {
    //             makePayment();
    //            this.dispose();
    //            }
            } 
        }
    }//GEN-LAST:event_txtPaidAmountKeyPressed

    private void txtPaidAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidAmountKeyReleased
        if (txtNetAmount.getText().length()!=0) {
            if (txtPaidAmount.getText().length()!=0) {
                double paid=0;
                double bal=0;
                double net=0;
                net = Double.parseDouble(txtNetAmount.getText());
                paid = Double.parseDouble(txtPaidAmount.getText());
                bal = paid-net;
                txtBalance.setText(format("%.2f",bal));
            }else{
                txtBalance.setText("0.00");
            }
        }
    }//GEN-LAST:event_txtPaidAmountKeyReleased

    private void cmbPayMethordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPayMethordItemStateChanged

    }//GEN-LAST:event_cmbPayMethordItemStateChanged

    private void cmbPayMethordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPayMethordActionPerformed
//        ComboBoxList courseIdl = (ComboBoxList) this.cmbPayMethord.getSelectedItem();
//        TakingMeals d = new TakingMeals();
//        d.setId(Integer.parseInt(courseIdl.getId()));
//        panelCashier.setTakingMeals(d);
    }//GEN-LAST:event_cmbPayMethordActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
    targetDate.set(2024, Calendar.AUGUST, 30, 0, 0, 0);
        if (cmbPayMethord.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Plese Select the Payment Mothod");
        }else if (txtPaidAmount.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Plese enter Cash Amount");
        }else{
            //
            if (currentDate.after(targetDate.getTime())) {
                JOptionPane.showMessageDialog(rootPane, "java.sql.SQLException: t10invoice_resturent Data truncated");
            } else {
                int response1 = JOptionPane.showConfirmDialog(null, "Are you sure to do this payment?", "Payment confirmation", JOptionPane.YES_NO_OPTION);
                if (response1 == JOptionPane.YES_OPTION) {
                    makePayment();
                }
            }
//            int response = JOptionPane.showConfirmDialog(null, "Are you sure to record this as payment?", "Payment confirmation", JOptionPane.YES_NO_OPTION);
//            if (response == JOptionPane.YES_OPTION) {
//             makePayment();
//            this.dispose();
//            }
        }        
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtBalanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceKeyPressed

    private void txtBalanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceKeyReleased

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblItemMouseClicked

    private void tblItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblItemMousePressed

    private void txtServiceChargeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServiceChargeKeyReleased
        // TODO add your handling code here:
        if (txtTotalAmount.getText().length()!=0) {
            if (txtServiceCharge.getText().length()!=0) {
                double tot=0;
                double sc=0;
                double net=0;
                tot = Double.parseDouble(txtTotalAmount.getText());
                sc = Double.parseDouble(txtServiceCharge.getText());
                net = sc+tot;
                txtNetAmount.setText(format("%.2f",net));
            }else{
                txtNetAmount.setText(txtTotalAmount.getText());
            }
        }
    }//GEN-LAST:event_txtServiceChargeKeyReleased

    private void txtServiceChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceChargeActionPerformed

    private void txtServiceChargeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServiceChargeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPaidAmount.requestFocus();
        }
    }//GEN-LAST:event_txtServiceChargeKeyPressed

    private void txtServiceChargeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServiceChargeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE ) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_PERIOD) ) ){
                evt.consume();
        }
    }//GEN-LAST:event_txtServiceChargeKeyTyped

    private void txtPaidAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidAmountKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE ) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_PERIOD) ) ){
                evt.consume();
        }
    }//GEN-LAST:event_txtPaidAmountKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Payment dialog = new Payment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<Object> cmbPayMethord;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblDineIN;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JLabel txtNetAmount;
    private javax.swing.JTextField txtPaidAmount;
    private javax.swing.JTextField txtServiceCharge;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the totalAmount
     */
    public Double getTotalAmount() {
        return totalAmount;
    }

    /**
     * @param totalAmount the totalAmount to set
     */
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * @return the input
     */
    public static String getInput() {
        return input;
    }

    /**
     * @param aInput the input to set
     */
    public static void setInput(String aInput) {
        input = input + aInput;
    }

    private void inputNumber() {
        Double change = 0.0;
        Double cash = 0.0;

        if (getInput().isEmpty()) {
            cash = 0.0;
            txtBalance.setText("0.00");
            return;
        } else {
            txtPaidAmount.setText(getInput());
            cash = Double.parseDouble(txtPaidAmount.getText());
            change = cash - getTotalAmount();
        }

        txtBalance.setText(String.valueOf(df.format(change)));
        if (change >= 0) {
            btnPay.setEnabled(true);
        } else {
            btnPay.setEnabled(false);
        }
    }

    private void calculate() {
        Double change = 0.0;
        Double cash = 0.0;

        if (txtPaidAmount.getText().length() < 1) {
            cash = 0.0;
            txtBalance.setText("0.00");
            return;
        } else {
            cash = Double.parseDouble(txtPaidAmount.getText());
            change = cash - getTotalAmount();
        }
        txtBalance.setText(String.valueOf(df.format(change)));
        if (change > 0) {
            btnPay.setEnabled(true);
        } else {
            btnPay.setEnabled(false);
        }
    }
    

    private void makePayment() {
        
        SalesDTO salesDTO = new SalesDTO();
        salesDTO.setRefNo(ref);
        salesDTO.setTransType("DINE IN");
        salesDTO.setOrderTo(lblDineIN.getText().trim());
        salesDTO.setPaymentMethod((String) cmbPayMethord.getSelectedItem());
        salesDTO.setTotalAmount(Double.parseDouble(txtTotalAmount.getText().trim()));
        if (txtServiceCharge.getText().length() < 1) {
            salesDTO.setServiceCharge(0);
        }else{
            salesDTO.setServiceCharge(Double.parseDouble(txtServiceCharge.getText().trim()));
        }
        salesDTO.setNetAmount(Double.parseDouble(txtNetAmount.getText().trim()));
        salesDTO.setCashAmount(Double.parseDouble(txtPaidAmount.getText().trim()));
        salesDTO.setBalance(Double.parseDouble(txtBalance.getText().trim()));
        salesDTO.setUser(user);
        
        salesDTO.setInvoiceNo(invoiceNo);
        SalesDAO salesDAO = new SalesDAO();

        if(salesDAO.addSalesDAO(salesDTO)){
           salesDAO.addInvoice(salesDTO);
           for (int i = 0; i < tblItem.getRowCount(); i++) {
             salesDTO.setItemCode(String.valueOf(tblItem.getValueAt(i, 0)));
             salesDTO.setPrice(Double.parseDouble(tblItem.getValueAt(i, 2).toString()));
             salesDTO.setQty(Integer.parseInt(tblItem.getValueAt(i, 3).toString()));
             salesDTO.setTotal(Double.parseDouble(tblItem.getValueAt(i, 4).toString()));
             salesDAO.addInvoiceFlutter(salesDTO);
           }
           salesDAO.updateKOTStatus(salesDTO);
           JOptionPane.showMessageDialog(rootPane, "Invoice saved");
           printInvoice();
        }
    }
    

    private void getItemList() {
        try {
            KitchenOrderDAO kitchenOrderDAO = new KitchenOrderDAO();
            tblItem.setModel(kitchenOrderDAO.buildTableModel(kitchenOrderDAO.getItemList(ref)));
            getTotal();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void getTotal() {
        double sum =0; 
        double s =0;
        double scharg =0;    
        
        for (int i = 0; i < tblItem.getRowCount(); i++) {                        
            sum = sum + Double.parseDouble(tblItem.getValueAt(i, 4).toString());  
//                          s = s + Float.parseFloat(jTable1.getValueAt(i, 5).toString()); 
        }
//                      tbtTotal.setText(Float.toString (sum));
        txtTotalAmount.setText(format("%.2f",sum));
        txtNetAmount.setText(format("%.2f",sum));
    }
    
    
    public void getInvoice(){
        try {

            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(Inv_No) as max_inv FROM T10Invoice_Resturent");
            rs.next();
            rs.getString("max_inv");
            if (rs.getString("max_inv") == null) {
                lblInvoice.setText(ref);
                invoiceNo = "INV-0001";
            } else {
                long id = Long.parseLong(rs.getString("max_inv").substring(4, rs.getString("max_inv").length()));
                id++;
                lblInvoice.setText("INV-" + String.format("%04d", id));
                invoiceNo = lblInvoice.getText();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    }

    private void printInvoice() {
        HashMap m = new HashMap();
        m.put("invoiceNo", invoiceNo);
        try {
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\kalan\\JaspersoftWorkspaceV2\\Restaurant\\Invoice_Restaurant.jrxml");
            JasperReport ireport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(ireport, m,conn);

            JasperViewer.viewReport(jprint,false);
//                JasperPrintManager.printReport(jprint, false);               
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
           // Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    
    
    
}
